Add TLS support
calendar-team/calendar-backend pull request #6
Opened 2023-08-26 15:19 UTC by aguzovatii

2023-08-29 19:45 UTC, aguzovatii commented
The TLS certificate was issued by [Let's Encrypt](https://letsencrypt.org/)
I requested the certificate using [certbot](https://certbot.eff.org/) by following the tutorial from [here](https://certbot.eff.org/instructions?ws=other&os=pip).
Please note that the certificate should be renewed automatically by certbot because I added a cron.

2023-08-30 10:34 UTC, Guzovatii-L approved these changes
you are smart!

2023-08-30 14:30 UTC, DianaJacota requested changes

2023-08-30 14:58 UTC, aguzovatii commented on .github/workflows/deploy_on_ec2.yml
> +    branches: [ "add_tls_support" ]
Good catch!
Changed in e49589ae4e85d975fe8d8a2567c5a97d0dc67485

2023-08-31 16:27 UTC, DianaJacota approved these changes

2023-08-31 16:29 UTC, Guzovatii-L approved these changes

2023-08-31 16:30 UTC, merged